---
- name: Pull and Run docker image of shivraj25/calculator
  hosts: all
  tasks:
    - name: Pull shivraj25/calculator
      docker_image:
        name: shivraj25/calculator
        source: pull

    - name: Create default containers
      docker_container:
        name: c1
        image: shivraj25/calculator
        state: present

- name: Running MYSQL Database as Docker Container using Ansible.
  hosts: all

  vars:
    db_volume: db_data

  tasks:
    - name: Launch mysql database container
      docker_container:
        name: mysql-standalone-test
        image: mysql:5.7
        volumes:
          - "{{ db_volume }}:/var/lib/mysql"
        restart: true
        env:
          MYSQL_ROOT_PASSWORD: Shivraj@25
          MYSQL_DATABASE: testdb
          MYSQL_USER: Shivraj
          MYSQL_PASSWORD: Shivraj@25
        ports:
          - "33307:3306"
